name: clip_prefix_caption
channels:
  - defaults
dependencies:
  - python>=3.10.11
  - pip>=21
  - numpy=1.26.0
  - scikit-image=0.22.0
  - pip:
      - transformers~=4.34.0
      - ftfy
      - regex
      - numpy
      - tqdm
      - git+https://github.com/openai/CLIP.git
